### ISSUE TITLE
Diogo, go home and call me

### ISSUE THREAD

**Issue by toemmelae** [NTBJass/sandbox#1]
mobilephone

**Comment by JoaoDiogoF** [comment]
dont want to!
#

1. bla

[https://www.google.ch/search?q=gay+porn&client=firefox-b-ab&dcr=0&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjylKu7huDZAhUC_SwKHZ1IDlcQ_AUICigB&biw=1350&bih=806#imgrc=yve-4exnwLhZyM:](url)
